from __future__ import annotations

import ast
import io
import tokenize
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACKAGE = ROOT / "nanopa_twin"

FORBIDDEN = (
    "reproduction of",
    "based on the paper",
    "re-implementation",
    "following the authors",
    "as described by",
    "generated by",
    "ai-assisted",
    "skeleton",
    "placeholder",
    "todo from paper",
    "comprehensive",
    "cutting-edge",
    "seamlessly",
    "leveraging",
    "utilize",
    "delve",
    "holistic",
    "meticulously",
    "it's worth noting",
    "in conclusion",
    "state-of-the-art",
)


def _python_files() -> list[Path]:
    return sorted(PACKAGE.rglob("*.py")) + sorted((ROOT / "tests").rglob("*.py"))


def test_sources_have_no_docstrings() -> None:
    offenders: list[str] = []
    for path in _python_files():
        tree = ast.parse(path.read_text(encoding="utf-8"))
        if ast.get_docstring(tree) is not None:
            offenders.append(str(path))
        for node in ast.walk(tree):
            if isinstance(
                node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)
            ) and ast.get_docstring(node):
                offenders.append(f"{path}:{node.name}")
    assert offenders == []


def test_sources_have_no_comments() -> None:
    offenders: list[str] = []
    for path in _python_files():
        text = path.read_text(encoding="utf-8")
        for token in tokenize.generate_tokens(io.StringIO(text).readline):
            if token.type == tokenize.COMMENT:
                offenders.append(f"{path}:{token.start[0]}")
    assert offenders == []


def _is_emoji(char: str) -> bool:
    point = ord(char)
    return (
        0x2600 <= point <= 0x27BF
        or 0x1F000 <= point <= 0x1FAFF
        or point in (0x2764, 0x2B50, 0x2728)
    )


def test_prose_avoids_forbidden_language() -> None:
    targets = [ROOT / "README.md", ROOT / "Makefile"]
    for path in targets:
        lowered = path.read_text(encoding="utf-8").lower()
        present = [phrase for phrase in FORBIDDEN if phrase in lowered]
        assert present == [], f"{path}: {present}"


def test_prose_has_no_emoji() -> None:
    targets = [ROOT / "README.md", ROOT / "Makefile"]
    for path in targets:
        text = path.read_text(encoding="utf-8")
        assert not any(_is_emoji(c) for c in text), str(path)
